import type { Faction } from "./types";

export const DWARVES: Faction = {
  id: "dwarves",
  name: "Bronzebeard Clan",
  grandFaction: "alliance",
  allegiance: "Alliance",
  crest: "/assets/alliance/dwarves/crest.webp",
  colorKey: "dwarves",
  icon: "/assets/alliance/dwarves/crest.webp",
  theme: "Stubborn, heavily armed, ranged firepower and aerial prowess.",
  playstyle: "Ranged-dominant with the best guns in the game. Extremely tough and stubborn (high Morale bonuses). Slow-moving but devastating at range. Close combat is functional but not their strength — they want to shoot you to pieces before you reach them.",
  mechanic: {
    name: "Stoneborn Resolve",
    description: "Dwarven models add +1 to Morale tests (stacks with Command Aura). Dwarves almost never break.",
  },
  strengths: "Hardest-hitting ranged weapons, longest range, highest Morale, tough infantry, gryphon air support",
  weaknesses: "Slowest faction, limited magic, few Magical units for Mana/Dispel",
  ratings: { offense: 3, defense: 4, magic: 2, speed: 2 },
  upcoming: true,
  upcomingHint: "Army book in progress — unit profiles may change",
  units: [
    {
      name: "Mountain King",
      subfaction: "Dwarf",
      tier: "Hero",
      archetype: "Melee Bruiser",
      keywords: [],
      description: "Ancient warrior-lord of the deep halls. Racial: Stoneform (once per game, remove all debuffs and +1 DEF until end of round). Storm Bolt stuns priority targets, Thunder Clap disrupts formations, Avatar transforms him into stone.",
      equipment: ["Dwarven Hammer", "Greatsword", "Halberd", "Shield", "Plate Armor", "Mail"],
      stats: { MOV: 5, ATK: 4, SKL: 3, STR: 5, TGH: 5, DEF: 3, INI: 3, WND: 5, PTS: 145 },
      retinue: { unitName: "Ironforge Guard", min: 1, max: 2, specialRule: "King's Guard: Retinue Ironforge Guard may use Shatter Soul — destroy 1 guard to negate all damage from a single non-Blast hit on the Mountain King." },
      heroData: {
        className: "Mountain King",
        classAbility: { name: "Battle Cry", cost: "Once per game", type: "Buff", description: "All friendly models within 6\" gain +1 ATK die until end of round" },
        globals: [
          { name: "Heroic Strike", cost: "1 Mana", type: "Instant", description: "Next melee attack this activation deals +2 bonus damage" },
          { name: "Battle Shout", cost: "2 Mana", type: "Buff", description: "Friendlies within 6\" gain +1 ATK until end of round" },
        ],
        specs: [
          {
            name: "Mountain King",
            abilities: [
              { name: "Storm Bolt", cost: "2 Mana", type: "Spell Shoot", description: "Range 12\", STR 5. If target wounded, cannot move or attack next activation (stunned)" },
              { name: "Thunder Clap", cost: "2 Mana", type: "Instant", description: "All enemies within 3\" suffer STR 4 hit and -1 ATK until end of round" },
            ],
            ultimate: { name: "Avatar", cost: "Once per battle", type: "Buff", description: "Gain +2 TGH, +1 ATK die, and immunity to debuffs until end of round" },
          },
          {
            name: "Protection",
            abilities: [
              { name: "Shield Wall", cost: "1 Mana", type: "Reaction", description: "+2 DEF until end of round. Requires Shield" },
              { name: "Taunt", cost: "Passive", type: "Buff", description: "Gain Taunt keyword permanently" },
            ],
            ultimate: { name: "Last Stand", cost: "Once per battle", type: "Instant", description: "Restore to full WND and gain +2 DEF until end of round" },
          },
        ],
      },
    },
    {
      name: "Dwarf Ranger",
      subfaction: "Dwarf",
      tier: "Baseline",
      archetype: "Core Ranged",
      keywords: ["Decisive Blow [1]"],
      description: "Sturdy ranged specialists with the hardest-hitting ranged weapons in the game. RSTR 5 wounds on 3+ against most infantry. 30\" base range keeps them shooting before anyone else.",
      equipment: ["Rifle", "Crossbow", "Stormhammer", "Dwarven Hammer", "Mail", "Leather"],
      stats: { MOV: 4, ATK: 2, SKL: 4, STR: 3, TGH: 4, DEF: 5, INI: 3, WND: 3, PTS: 50 },
    },
    {
      name: "Ironforge Guard",
      subfaction: "Dwarf",
      tier: "Baseline",
      archetype: "Core Infantry",
      keywords: [],
      description: "The shield wall of Ironforge. Heavily armored Dwarf infantry who hold the line while Rangers shoot over their heads. Slower than Footmen but just as tough, with Dwarven stubbornness keeping them planted.",
      equipment: ["Dwarven Hammer", "Shield", "Plate Armor", "Mail"],
      stats: { MOV: 4, ATK: 2, SKL: 4, STR: 4, TGH: 5, DEF: 4, INI: 2, WND: 3, PTS: 45 },
    },
    {
      name: "Thane",
      subfaction: "Dwarf",
      tier: "Elite",
      archetype: "Heavy Infantry",
      keywords: ["Decisive Blow [2]"],
      description: "Veteran Dwarf lord. Heavy weapon, heavy armor, devastating strikes. High WND. Slow but extremely dangerous.",
      equipment: ["Dwarven Hammer", "Greatsword", "Halberd", "Shield", "Plate Armor", "Mail"],
      stats: { MOV: 4, ATK: 3, SKL: 3, STR: 5, TGH: 5, DEF: 3, INI: 2, WND: 4, PTS: 85 },
    },
    {
      name: "Gryphon Rider",
      subfaction: "Dwarf",
      tier: "Elite",
      archetype: "Flying Shock Cavalry",
      keywords: ["Fly", "Momentum [1]"],
      description: "Dwarf on a gryphon. Flying charge plus throwing hammer ranged. Counts against both Mounted and Elite limits.",
      equipment: ["Dwarven Hammer", "Stormhammer", "Mail"],
      stats: { MOV: 10, ATK: 3, SKL: 3, STR: 4, TGH: 4, DEF: 4, INI: 3, WND: 3, PTS: 95 },
      dualSlot: "Mounted + Elite",
    },
  ],
  composition: [
    { size: "Skirmish (500 pts)", baseline: "3-5", mounted: "0-2", elite: "0-2", hero: "1" },
    { size: "Standard (750 pts)", baseline: "4-7", mounted: "0-3", elite: "1-3", hero: "1-2" },
    { size: "Large (1000+ pts)", baseline: "5-9", mounted: "1-4", elite: "2-5", hero: "2-3" },
  ],
};
