import type { Faction } from "./types";

export const FORSAKEN: Faction = {
  id: "forsaken",
  name: "The Forsaken",
  grandFaction: "horde",
  allegiance: "Horde",
  icon: "/assets/horde/forsaken/crest.webp",
  crest: "/assets/horde/forsaken/crest.webp",
  colorKey: "forsaken",
  theme: "Chemical warfare, poison, and plague. Free-willed undead who weaponize alchemy and biological agents against the living.",
  playstyle: "Debuff and attrition through Poison (damage over time) and Plague (stat degradation). Apply both to a target and the Poison wound ignores DEF saves. Blight tokens deny ground. Dark Rangers snipe from Stealth. Dread Riders spread Plague on the charge.",
  mechanic: {
    name: "Blight",
    description: "Forsaken models with the Plague keyword can place a Blight token within 3\" when they activate (free, once per activation). Enemy models on Blight suffer 1 wound (DEF save). Persists 2 rounds.",
  },
  strengths: "Two interlocking status effects (Poison + Plague synergy), Blight area denial, Stealth assassins, best ranged accuracy (SKL 2+), Undead ignore Morale",
  weaknesses: "Low raw damage (rely on debuffs first), Undead can't be healed at all, split Morale mechanics (Living Apothecaries test Morale), moderate base stats",
  ratings: { offense: 2, defense: 3, magic: 4, speed: 3 },
  specialRules: [
    "Poison: 1 wound at start of victim's next activation (DEF save). If also Plagued, ignores DEF saves.",
    "Plague: -1 TGH until end of round. Does not stack beyond -1.",
    "Blight: Plague keyword models place tokens when activated. Enemies on Blight suffer 1 wound (DEF save). Persists 2 rounds.",
  ],
  units: [
    {
      name: "Dark Lady",
      subfaction: "Forsaken",
      tier: "Hero",
      archetype: "Ranged / Commander",
      keywords: ["Magical", "Undead", "Stealth", "Decisive Blow [2]"],
      description: "Supreme commander. Black Arrow applies Poison + -1 DEF on ranged hits. Charm dominates enemy models. Racial: Undying Will (Undead — immune to Morale and Taunt, cannot be healed).",
      equipment: ["Longbow", "Dagger", "Leather"],
      stats: { MOV: 6, ATK: 3, SKL: 2, STR: 5, TGH: 3, DEF: 5, INI: 6, WND: 4, PTS: 130 },
      heroData: {
        className: "Dark Ranger",
        classAbility: { name: "Charm", cost: "Once per game", type: "Instant", description: "Target enemy non-Hero within 8\" switches sides for 1 round, then destroyed" },
        globals: [
          { name: "Black Arrow", cost: "2 Mana", type: "Buff", description: "Self. Ranged attacks apply Poison (on wound, no unsaved wound required). Poisoned targets also suffer -1 DEF" },
          { name: "Hunter's Mark", cost: "1 Mana", type: "Debuff", description: "Enemy within 18\" suffers -1 DEF. All friendly Forsaken gain +1 to hit vs marked target" },
        ],
        specs: [
          {
            name: "Dark Ranger",
            abilities: [
              { name: "Silence", cost: "2 Mana", type: "Debuff", description: "Enemy within 12\" cannot use abilities until end of round" },
              { name: "Dark Pursuit", cost: "1 Mana", type: "Buff", description: "Gain Stealth and Disengage until this Hero attacks" },
            ],
            ultimate: { name: "Withering Volley", cost: "Once per battle — 3 Mana", type: "Blast", description: "Small Blast 3\", STR 5, Range 24\". All hit become permanently Plagued (does not expire)" },
          },
          {
            name: "Banshee",
            abilities: [
              { name: "Life Drain", cost: "2 Mana", type: "Spell Shoot", description: "Range 12\", STR 4. Heals WND equal to wounds dealt (bypasses Undead restriction)" },
              { name: "Wail of the Banshee", cost: "2 Mana", type: "Instant", description: "All enemies within 4\" take Morale test at -2. Undead/Mechanical immune" },
            ],
            ultimate: { name: "Possession", cost: "Once per battle — 3 Mana", type: "Instant", description: "Enemy non-Hero within 6\" permanently switches sides" },
          },
        ],
      },
    },
    {
      name: "Grand Apothecary",
      subfaction: "Forsaken",
      tier: "Hero",
      archetype: "Plague Caster / Debuff",
      keywords: ["Magical", "Plague"],
      retinue: { unitName: "Apothecary", min: 1, max: 1, specialRule: "Lab Assistant: The retinue Apothecary generates +1 Mana while within 4\" of the Grand Apothecary." },
      description: "Supreme alchemist. Master of chemical warfare — Plague Bombs, mass debuffs, Blight detonation. New Plague permanently applies both Plagued AND Poisoned. Living — tests Morale, can be healed.",
      equipment: ["Plague Staff", "Robes/None"],
      stats: { MOV: 5, ATK: 2, SKL: 4, STR: 3, TGH: 3, DEF: 5, INI: 3, WND: 3, PTS: 115 },
      heroData: {
        className: "Apothecary",
        classAbility: { name: "New Plague", cost: "Once per game", type: "Blast", description: "Large Blast 5\", Range 12\". All enemies hit become Plagued AND Poisoned permanently (neither expires). No save" },
        globals: [
          { name: "Plague Bomb", cost: "2 Mana", type: "Blast", description: "Small Blast 3\", Range 12\", STR 3. All hit become Plagued. Creates Blight token at impact" },
          { name: "Miasma", cost: "1 Mana", type: "Debuff", description: "All enemies within 3\" suffer -1 to hit rolls until end of round" },
        ],
        specs: [
          {
            name: "Plague Doctor",
            abilities: [
              { name: "Toxic Injection", cost: "1 Mana", type: "Buff", description: "Friendly model within 6\" gains Poison on melee attacks this round" },
              { name: "Adaptive Toxin", cost: "2 Mana", type: "Debuff", description: "Enemy within 12\" suffers -1 TGH. If already Poisoned or Plagued, also -1 ATK" },
            ],
            ultimate: { name: "Perfected Strain", cost: "Once per battle — 3 Mana", type: "Debuff", description: "Enemy within 12\" becomes permanently Plagued and Poisoned. Also -1 ATK, -1 DEF for the rest of the game. No save" },
          },
          {
            name: "Blightcaller",
            abilities: [
              { name: "Blight Spray", cost: "1 Mana", type: "Spell Shoot", description: "Range 8\", STR 3. Target becomes Plagued. Creates Blight token at target's position" },
              { name: "Creeping Death", cost: "2 Mana", type: "Instant", description: "All Blight tokens detonate — enemies within 2\" suffer 1 wound (DEF save) and become Plagued. Tokens not removed" },
            ],
            ultimate: { name: "Wrathgate", cost: "Once per battle — 4 Mana", type: "Blast", description: "Large Blast 5\", Range 18\", STR 5. All hit become Plagued. Creates Blight across blast area. Friendlies also affected" },
          },
        ],
      },
    },
    {
      name: "Deathguard",
      subfaction: "Forsaken",
      tier: "Baseline",
      archetype: "Core Infantry",
      keywords: ["Undead"],
      description: "Rank-and-file soldiers of Undercity. Undead: never break, never heal. 3 loadouts: Sword+Shield (DEF 4+), Dual Blades (4 ATK), Greatsword (AP 1, DMG 2, INI -1). Any loadout can upgrade to Poisoned Blades (+5 pts).",
      equipment: ["Sword+Shield / Dual Blades / Greatsword", "Mail"],
      loadouts: [
        { name: "Sword + Shield", equipment: ["Sword", "Shield", "Mail"], statOverrides: { DEF: 4 } },
        { name: "Dual Blades", equipment: ["Dual Blades", "Mail"], statOverrides: { ATK: 4 } },
        { name: "Greatsword", equipment: ["Greatsword", "Mail"], statOverrides: { INI: 2 } },
      ],
      stats: { MOV: 5, ATK: 3, SKL: 4, STR: 3, TGH: 3, DEF: 5, INI: 3, WND: 2, PTS: 35 },
    },
    {
      name: "Dread Rider",
      subfaction: "Forsaken",
      tier: "Mounted",
      archetype: "Pursuit Cavalry",
      keywords: ["Undead", "Fear"],
      description: "Undead knights on skeletal warhorses. Dread Charge applies Plagued and forces Morale test. Blighted Lance grants Momentum [1] and AP 1 on charge.",
      equipment: ["Sword", "Blighted Lance", "Shield", "Mail"],
      stats: { MOV: 8, ATK: 3, SKL: 4, STR: 4, TGH: 4, DEF: 5, INI: 3, WND: 3, PTS: 65 },
    },
    {
      name: "Dark Ranger",
      subfaction: "Forsaken",
      tier: "Elite",
      archetype: "Elite Ranged / Sniper",
      keywords: ["Undead", "Stealth", "Decisive Blow [1]", "Precision Shot"],
      description: "SKL 2+ — the most accurate ranged unit in the game. Stealth keeps them hidden beyond 12\". Precision Shot picks targets out of melee. Decisive Blow [1] punishes on natural 6s.",
      equipment: ["Longbow", "Dagger", "Leather"],
      stats: { MOV: 6, ATK: 3, SKL: 2, STR: 4, TGH: 3, DEF: 6, INI: 5, WND: 2, PTS: 75 },
    },
    {
      name: "Deathstalker",
      subfaction: "Forsaken",
      tier: "Elite",
      archetype: "Melee Assassin",
      keywords: ["Undead", "Stealth", "Disengage"],
      description: "Stealth in, poisoned blades strike, Disengage out. Poison deals 1 wound at start of victim's next activation. If target is also Plagued, Poison ignores DEF saves.",
      equipment: ["Poisoned Daggers", "Leather"],
      stats: { MOV: 6, ATK: 3, SKL: 3, STR: 3, TGH: 3, DEF: 6, INI: 6, WND: 2, PTS: 70 },
    },
    {
      name: "Abomination",
      subfaction: "Forsaken",
      tier: "Elite",
      archetype: "Heavy Tank / Control",
      keywords: ["Undead", "Cleave", "Fear"],
      description: "Stitched corpse monstrosity. Meat Hook drags enemies into base contact (3+ on D6). Plague Burst on death applies Plagued + 1 wound to nearby non-Undead.",
      equipment: ["Cleaver", "Plate Armor"],
      stats: { MOV: 4, ATK: 3, SKL: 4, STR: 5, TGH: 5, DEF: 4, INI: 1, WND: 5, PTS: 90 },
    },
    {
      name: "Apothecary",
      subfaction: "Forsaken",
      tier: "Elite",
      archetype: "Plague & Poison Support",
      keywords: ["Magical", "Plague"],
      description: "Swiss-army support: hurls Plague Vials (applies Plagued on wound), deploys Blight tokens, and buffs allies with Poison via Toxin Application. Living — tests Morale but can be healed.",
      equipment: ["Plague Staff", "Plague Vial", "Leather"],
      stats: { MOV: 5, ATK: 2, SKL: 4, STR: 3, TGH: 3, DEF: 6, INI: 3, WND: 2, PTS: 55 },
    },
  ],
  composition: [
    { size: "Skirmish (500 pts)", baseline: "3-6", mounted: "0-1", elite: "0-2", hero: "1" },
    { size: "Standard (750 pts)", baseline: "4-8", mounted: "0-2", elite: "1-4", hero: "1-2" },
    { size: "Large (1000+ pts)", baseline: "5-10", mounted: "0-3", elite: "2-5", hero: "2" },
  ],
};

