import type { Faction } from "./types";

export const HUMANS: Faction = {
  id: "humans",
  name: "Kingdom of Stormwind",
  grandFaction: "alliance",
  allegiance: "Alliance",
  isBase: true,
  icon: "/assets/alliance/humans/crest.webp",
  crest: "/assets/alliance/humans/crest.webp",
  banner: "/assets/alliance/humans/banner.png",
  colorKey: "humans",
  theme: "Disciplined, versatile, faith-powered. The backbone of the Alliance.",
  playstyle: "Balanced and adaptable. Strong defensive line with heavy armor infantry, supported by paladins (Taunt/healing) and priests (buffs). Solid ranged with crossbowmen. Good cavalry for flanking. No glaring weakness but no extreme specialty — they win through discipline and flexibility.",
  mechanic: {
    name: "Devotion Auras",
    description: "Buff abilities cast by Human models cost 1 less Mana (minimum 1).",
  },
  strengths: "High DEF across the board, efficient buffs, versatile roster",
  weaknesses: "Low INI (heavy armor everywhere), no Regeneration or Berserker, predictable",
  ratings: { offense: 3, defense: 4, magic: 3, speed: 3 },
  units: [
    {
      name: "Paladin",
      subfaction: "Human",
      tier: "Hero",
      archetype: "Tank / DPS",
      keywords: ["Magical"],
      description: "The quintessential Alliance Hero — faith, plate, and a blessed blade. Racial: Versatility (may use 2 abilities per activation, second costs +1 Mana). Protection Paladins are unkillable walls. Retribution Paladins channel the Light into devastating melee strikes.",
      equipment: ["Runesword", "Plate Armor", "Shield (Protection only)"],
      stats: { MOV: 5, ATK: 4, SKL: 3, STR: 5, TGH: 5, DEF: 4, INI: 3, WND: 5, PTS: 140 },
      retinue: { unitName: "Footman", min: 1, max: 2, specialRule: "Honor Guard: Retinue Footmen gain +1 Morale while within 4\" of the Paladin." },
      heroData: {
        className: "Paladin",
        classAbility: { name: "Lay on Hands", cost: "Once per game", type: "Instant", description: "Fully heal one friendly model within 2\"" },
        globals: [
          { name: "Holy Light", cost: "2 Mana", type: "Instant", description: "Restore 2 WND to a friendly model within 6\"" },
        ],
        specs: [
          {
            name: "Protection",
            abilities: [
              { name: "Shield of the Righteous", cost: "1 Mana", type: "Reaction", description: "Negate 1 incoming wound to this model" },
              { name: "Inspiring Presence", cost: "Passive", type: "Buff", description: "Friendly models within 6\" gain +1 Morale" },
              { name: "Taunt", cost: "Passive", type: "Buff", description: "Gain the Taunt keyword permanently" },
            ],
            ultimate: { name: "Divine Shield", cost: "Once per battle", type: "Buff", description: "Immune to all damage until end of round" },
          },
          {
            name: "Retribution",
            abilities: [
              { name: "Judgment", cost: "2 Mana", type: "Spell Shoot", description: "Range 12\", STR 5. Target suffers -1 DEF until end of round" },
              { name: "Seal Stance", cost: "Free Action", type: "Buff", description: "Choose a seal: Command (+1 ATK), Protection (+1 DEF), or Light (Heal 1 WND at start of activation)" },
              { name: "Crusader Strike", cost: "1 Mana", type: "Instant", description: "Next melee attack this activation gains +2 ATK dice" },
            ],
            ultimate: { name: "Avenging Wrath", cost: "Once per battle", type: "Buff", description: "Gain +2 ATK dice and +1 STR until end of round. All abilities cost 0 Mana this round" },
          },
        ],
      },
    },
    {
      name: "Archmage",
      subfaction: "Human",
      tier: "Hero",
      archetype: "Caster / Damage",
      keywords: ["Magical"],
      description: "Master of the arcane arts. Glass cannon — devastating spell damage but fragile. Racial: Versatility (may use 2 abilities per activation, second costs +1 Mana). Three schools: Frost controls, Arcane sustains, Fire explodes.",
      equipment: ["Staff", "Robes/None"],
      stats: { MOV: 5, ATK: 2, SKL: 3, STR: 3, TGH: 3, DEF: 6, INI: 4, WND: 3, PTS: 115 },
      heroData: {
        className: "Mage",
        classAbility: { name: "Evocation", cost: "Once per game", type: "Instant", description: "Immediately gain 4 Mana" },
        globals: [
          { name: "Fireball", cost: "2 Mana", type: "Spell Shoot", description: "Ranged attack, STR 5, Range 18\"" },
          { name: "Arcane Intellect", cost: "2 Mana", type: "Buff", description: "Target Magical model generates +1 Mana next turn (1 Mana with Devotion Auras)" },
        ],
        specs: [
          {
            name: "Frost",
            abilities: [
              { name: "Frostbolt", cost: "2 Mana", type: "Spell Shoot", description: "STR 4, Range 18\". Target suffers -2 MOV until end of round" },
              { name: "Ice Barrier", cost: "2 Mana", type: "Buff", description: "Self: absorb next 2 wounds" },
            ],
            ultimate: { name: "Blizzard", cost: "Once per battle — 3 Mana", type: "Blast", description: "Large Blast 5\", STR 4, Range 18\". All hit targets cannot move next activation" },
          },
          {
            name: "Arcane",
            abilities: [
              { name: "Arcane Missiles", cost: "2 Mana", type: "Spell Shoot", description: "3 separate STR 4 attacks against one target, Range 18\"" },
              { name: "Brilliance Aura", cost: "3 Mana", type: "Buff", description: "Army generates +1 base Mana this round (2 Mana with Devotion Auras)" },
            ],
            ultimate: { name: "Arcane Power", cost: "Once per battle", type: "Buff", description: "Next 3 Spell Shoot abilities this round deal double damage" },
          },
          {
            name: "Fire",
            abilities: [
              { name: "Ignite", cost: "Passive", type: "Buff", description: "When Fireball kills a model, one enemy within 2\" of the killed model suffers a STR 4 hit" },
              { name: "Combustion", cost: "2 Mana", type: "Buff", description: "All Spell Shoot abilities this round gain +2 STR (1 Mana with Devotion Auras)" },
            ],
            ultimate: { name: "Pyroblast", cost: "Once per battle — 3 Mana", type: "Spell Shoot", description: "Ranged attack, STR 8, Range 18\", AP 2" },
          },
        ],
      },
    },
    {
      name: "Footman",
      subfaction: "Human",
      tier: "Baseline",
      archetype: "Core Infantry",
      keywords: ["Shield Wall"],
      isBaseUnit: true,
      description: "The Alliance backbone. Plate armor and discipline make them the toughest baseline unit. Shield Wall: when 2+ Footmen within 2\", Shield Footmen reroll one failed DEF save of 1.",
      equipment: ["Sword+Shield / Halberd", "Plate Armor"],
      loadouts: [
        { name: "Sword + Shield", equipment: ["Sword", "Shield", "Plate Armor"], statOverrides: { DEF: 3 } },
        { name: "Halberd", equipment: ["Halberd", "Plate Armor"], statOverrides: { INI: 2 } },
      ],
      stats: { MOV: 5, ATK: 2, SKL: 4, STR: 4, TGH: 5, DEF: 4, INI: 3, WND: 2, PTS: 35 },
    },
    {
      name: "Crossbowman",
      subfaction: "Human",
      tier: "Baseline",
      archetype: "Core Ranged",
      keywords: [],
      isBaseUnit: true,
      description: "Stormwind's ranged infantry. Reliable and disciplined. Standard 24\" range crossbows provide solid fire support. Not flashy, but cheap and effective in numbers.",
      equipment: ["Crossbow", "Sword", "Mail"],
      stats: { MOV: 5, ATK: 2, SKL: 4, STR: 4, TGH: 3, DEF: 5, INI: 3, WND: 2, PTS: 25 },
    },
    {
      name: "Knight",
      subfaction: "Human",
      tier: "Mounted",
      archetype: "Heavy Cavalry",
      keywords: ["Momentum [1]"],
      description: "Classic armored charge. High DEF, solid damage on impact. The hammer to the Footman's anvil.",
      equipment: ["Sword+Shield / Halberd", "Plate Armor"],
      loadouts: [
        { name: "Sword + Shield", equipment: ["Sword", "Shield", "Plate Armor"], statOverrides: { DEF: 3 } },
        { name: "Halberd", equipment: ["Halberd", "Plate Armor"], statOverrides: { INI: 2 } },
      ],
      stats: { MOV: 8, ATK: 4, SKL: 4, STR: 4, TGH: 5, DEF: 4, INI: 3, WND: 2, PTS: 60 },
    },
    {
      name: "Priest",
      subfaction: "Human",
      tier: "Elite",
      archetype: "Support / Buffer",
      keywords: ["Magical"],
      description: "Battlefield healer and support. Heal keeps models alive, Inner Fire buffs ATK, Smite provides ranged damage. Resurrection is the ultimate comeback ability.",
      equipment: ["Staff", "Robes/None"],
      stats: { MOV: 5, ATK: 2, SKL: 4, STR: 3, TGH: 3, DEF: 6, INI: 3, WND: 3, PTS: 60 },
    },
    {
      name: "Sorceress",
      subfaction: "Human",
      tier: "Elite",
      archetype: "Caster / Control",
      keywords: ["Magical"],
      description: "Kirin Tor-trained battle mage. SKL 3+ and battlefield control through slows (Frostbolt) and crowd control (Polymorph, Invisibility).",
      equipment: ["Staff", "Robes/None"],
      stats: { MOV: 5, ATK: 2, SKL: 3, STR: 3, TGH: 3, DEF: 6, INI: 4, WND: 3, PTS: 60 },
    },
    {
      name: "Champion",
      subfaction: "Human",
      tier: "Elite",
      archetype: "Melee Leader",
      keywords: [],
      isBaseUnit: true,
      description: "Veteran sub-commander. Masterwork Greatsword (AP 2) cuts through heavy armor. For Lordaeron! gives charging friendlies within 6\" +1 ATK. Inspiring Presence grants +1 Morale.",
      equipment: ["Masterwork Greatsword", "Plate Armor"],
      stats: { MOV: 5, ATK: 3, SKL: 3, STR: 5, TGH: 5, DEF: 4, INI: 2, WND: 3, PTS: 70 },
    },
  ],
  composition: [
    { size: "Skirmish (500 pts)", baseline: "3-6", mounted: "0-2", elite: "0-2", hero: "1" },
    { size: "Standard (750 pts)", baseline: "4-8", mounted: "0-3", elite: "1-3", hero: "1-2" },
    { size: "Large (1000+ pts)", baseline: "5-10", mounted: "1-4", elite: "2-5", hero: "2-3" },
  ],
};
