import type { Faction } from "./types";

export const SCOURGE: Faction = {
  id: "scourge",
  name: "Scourge",
  grandFaction: "scourge",
  allegiance: "Scourge",
  isBase: true,
  icon: "/images/scourge.webp",
  crest: "/images/scourge_crest.webp",
  svgIcon: "/icons/factions/scourge.svg",
  colorKey: "scourge",
  theme: "Undeath incarnate. The Lich King's army of skeletons, ghouls, and necromancers. Relentless, inevitable, endless.",
  playstyle: "Swarm and attrition. Flood the board with cheap Undead that never test Morale. Necromancers raise fallen models as new Skeletons — the army grows as models die. The Scourge doesn't outfight you — it outlasts you.",
  mechanic: {
    name: "Raise Dead",
    description: "When any non-summoned model (friend or foe) is destroyed within 6\" of a surviving Scourge Magical model, spend 1 Mana to place a Skeleton Warrior at the destroyed model's position.",
  },
  strengths: "Entire army immune to Morale, endless summoning/raising, overwhelming activation advantage, Fear on elites, frost debuffs",
  weaknesses: "Cannot heal anything (Undead), individual models weak, no shields, dependent on Heroes/Magical units for Mana, if Necromancers die the engine stops",
  ratings: { offense: 3, defense: 2, magic: 5, speed: 3 },
  units: [
    {
      name: "Death Knight (Mounted)",
      subfaction: "Scourge",
      tier: "Hero",
      archetype: "Heavy Cavalry",
      keywords: ["Undead", "Magical", "Momentum [1]"],
      description: "The Lich King's champion on a deathcharger. Runesword-wielding warrior-caster. Death Coil heals Undead or damages living. Bodyguard: 2 Ghouls. Specs: Unholy or Frost.",
      equipment: ["Runesword", "Death Plate"],
      stats: { MOV: 8, ATK: 4, SKL: 3, STR: 5, TGH: 5, DEF: 4, INI: 3, WND: 7, PTS: 150 },
      heroData: {
        className: "Death Knight",
        classAbility: { name: "Dark Ritual", cost: "Once per game", type: "Instant", description: "Destroy one friendly model within 2\" to immediately gain 5 Mana" },
        globals: [
          { name: "Death Coil", cost: "2 Mana", type: "Spell Shoot", description: "Range 12\", AP 1. Heal a friendly Undead model 2 WND or deal 2 WND to a living model" },
        ],
        specs: [
          {
            name: "Unholy",
            abilities: [
              { name: "Unholy Frenzy", cost: "2 Mana", type: "Buff", description: "Target Undead within 12\" gains +2 ATK but takes 1 Wound at round end" },
              { name: "Necrotic Aura", cost: "Passive", type: "Debuff", description: "6\" Aura. All enemies within take 1 Wound at end of round. Models killed in zone: place Skeleton for 0 Mana" },
            ],
            ultimate: { name: "Army of the Dead", cost: "Once per game", type: "Summon", description: "Destroy all bodyguards. Place 2 Skeleton Warriors within 6\" for each one destroyed" },
          },
          {
            name: "Frost",
            abilities: [
              { name: "Icy Touch", cost: "2 Mana", type: "Spell Shoot", description: "Range 18\". Target cannot use Rush or Charge actions" },
              { name: "Remorseless Winter", cost: "Passive", type: "Debuff", description: "4\" Aura. Enemies suffer -2 INI" },
            ],
            ultimate: { name: "Cold Breath", cost: "Once per game — 4 Mana", type: "Blast", description: "5\" Blast, STR 4, AP 1. Targets failing STR roll are Frozen (Hold only). Sacrifice bodyguard for STR 7" },
          },
        ],
      },
    },
    {
      name: "Death Knight (On Foot)",
      subfaction: "Scourge",
      tier: "Hero",
      archetype: "Heavy Infantry",
      keywords: ["Undead", "Magical"],
      description: "The Lich King's champion on foot. Runesword or Runeblade, can take Shield. Death Coil heals Undead or damages living. Bodyguard: 2 Skeleton Warriors. Specs: Unholy or Frost.",
      equipment: ["Runesword", "Runeblade", "Shield", "Death Plate", "Bone/Chain"],
      stats: { MOV: 5, ATK: 4, SKL: 3, STR: 5, TGH: 5, DEF: 4, INI: 3, WND: 5, PTS: 130 },
      heroData: {
        className: "Death Knight",
        classAbility: { name: "Dark Ritual", cost: "Once per game", type: "Instant", description: "Destroy one friendly model within 2\" to immediately gain 5 Mana" },
        globals: [
          { name: "Death Coil", cost: "2 Mana", type: "Spell Shoot", description: "Range 12\", AP 1. Heal a friendly Undead model 2 WND or deal 2 WND to a living model" },
        ],
        specs: [
          {
            name: "Unholy",
            abilities: [
              { name: "Unholy Frenzy", cost: "2 Mana", type: "Buff", description: "Target Undead within 12\" gains +2 ATK but takes 1 Wound at round end" },
              { name: "Necrotic Aura", cost: "Passive", type: "Debuff", description: "6\" Aura. All enemies within take 1 Wound at end of round. Models killed in zone: place Skeleton for 0 Mana" },
            ],
            ultimate: { name: "Army of the Dead", cost: "Once per game", type: "Summon", description: "Destroy all bodyguards. Place 2 Skeleton Warriors within 6\" for each one destroyed" },
          },
          {
            name: "Frost",
            abilities: [
              { name: "Icy Touch", cost: "2 Mana", type: "Spell Shoot", description: "Range 18\". Target cannot use Rush or Charge actions" },
              { name: "Remorseless Winter", cost: "Passive", type: "Debuff", description: "4\" Aura. Enemies suffer -2 INI" },
            ],
            ultimate: { name: "Cold Breath", cost: "Once per game — 4 Mana", type: "Blast", description: "5\" Blast, STR 4, AP 1. Targets failing STR roll are Frozen (Hold only). Sacrifice bodyguard for STR 7" },
          },
        ],
      },
    },
    {
      name: "Lich",
      subfaction: "Scourge",
      tier: "Hero",
      archetype: "Pure Caster",
      keywords: ["Undead", "Magical"],
      description: "Master of frost magic and necromancy. Frost Nova locks down enemies. Phylactery: when destroyed, roll D6 — on 4+, return at 1 WND within 6\" of a friendly Undead. Bodyguard: 3 Acolytes. Specs: Frost or Necromancy.",
      equipment: ["Bone Staff", "Rags/None"],
      stats: { MOV: 5, ATK: 1, SKL: 3, STR: 2, TGH: 2, DEF: 6, INI: 3, WND: 4, PTS: 120 },
      heroData: {
        className: "Lich",
        classAbility: { name: "Dark Ritual", cost: "Once per game", type: "Instant", description: "Destroy one friendly model within 2\" to immediately gain 5 Mana" },
        globals: [
          { name: "Frost Nova", cost: "2 Mana", type: "Debuff", description: "All enemies within 3\" cannot move next activation" },
        ],
        specs: [
          {
            name: "Frost",
            abilities: [
              { name: "Frostbolt", cost: "2 Mana", type: "Spell Shoot", description: "Range 24\", STR 4, AP 1. Target suffers -2 MOV until end of round" },
              { name: "Frost Armor", cost: "2 Mana", type: "Buff", description: "Target friendly within 6\" gains +2 DEF; attackers in melee suffer -1 ATK until end of round" },
            ],
            ultimate: { name: "Blizzard", cost: "Once per game — 4 Mana", type: "Blast", description: "Large Blast, STR 4, AP 1. All targets cannot move and suffer -2 ATK next round" },
          },
          {
            name: "Necromancy",
            abilities: [
              { name: "Free Raise Dead", cost: "Passive", type: "Buff", description: "Raise Dead costs 0 Mana for models destroyed within 6\" of this Hero" },
              { name: "Corpse Explosion", cost: "2 Mana", type: "Instant", description: "Destroy friendly Undead within 4\". Small Blast, STR 5, AP 1 to all enemies within 3\"" },
            ],
            ultimate: { name: "Mass Raise Dead", cost: "Once per game", type: "Summon", description: "Destroy all bodyguards. Raise ALL destroyed models within 12\" as Skeleton Warriors at no Mana cost" },
          },
        ],
      },
    },
    {
      name: "Skeleton Warrior",
      subfaction: "Scourge",
      tier: "Baseline",
      archetype: "Swarm Melee",
      keywords: ["Undead"],
      description: "The cheapest model in the game. Individually fragile, but Raise Dead creates an endless tide. Immune to Morale — they never break, they just keep coming.",
      equipment: ["Sword", "Bone/Chain", "Shield"],
      stats: { MOV: 4, ATK: 2, SKL: 5, STR: 3, TGH: 2, DEF: 5, INI: 3, WND: 1, PTS: 10 },
    },
    {
      name: "Crypt Fiend",
      subfaction: "Scourge",
      tier: "Baseline",
      archetype: "Ranged / Melee Hybrid",
      keywords: ["Undead", "Spider Climb"],
      description: "Undead nerubians — giant spider-like creatures. Tougher and more versatile than Skeleton Archers. Venom Spit (18\") provides ranged support while Claws fight in melee. Spider Climb ignores terrain penalties. Web grounds a Fly model once per game.",
      equipment: ["Claws", "Venom Spit", "Chitin"],
      stats: { MOV: 6, ATK: 3, SKL: 4, STR: 4, TGH: 4, DEF: 5, INI: 3, WND: 2, PTS: 35 },
    },
    {
      name: "Ghoul",
      subfaction: "Scourge",
      tier: "Baseline",
      archetype: "Fast Aggressive Melee",
      keywords: ["Undead", "Berserker"],
      description: "Fastest Scourge infantry. High ATK and STR for a baseline unit. Berserker pushes wounded Ghouls to 4 ATK dice. Glass cannon — DEF 6+ and WND 2 means they don't survive return fire.",
      equipment: ["Claws", "Rags/None"],
      stats: { MOV: 7, ATK: 3, SKL: 4, STR: 4, TGH: 3, DEF: 6, INI: 4, WND: 2, PTS: 30 },
    },
    {
      name: "Acolyte",
      subfaction: "Scourge",
      tier: "Baseline",
      archetype: "Support / Mana Battery",
      keywords: ["Magical"],
      description: "Living cultists — not Undead. Test Morale normally and can be healed. Provide Magical keyword for Dispels and fuel Raise Dead. As Necromancer bodyguards, generate 1 Mana for every 2 alive.",
      equipment: ["Bone Staff", "Rags/None"],
      stats: { MOV: 5, ATK: 1, SKL: 5, STR: 2, TGH: 3, DEF: 6, INI: 3, WND: 2, PTS: 15 },
    },
    {
      name: "Death Knight (Elite)",
      subfaction: "Scourge",
      tier: "Elite",
      archetype: "Melee Leader",
      keywords: ["Undead", "Magical"],
      description: "Lesser death knights — fallen warriors raised by the Lich King's will. Choose one spec ability: Frost (Frost Strike: -2 MOV, -1 ATK), Unholy (Dark Command: +2 ATK to friendly Undead), or Blood (Death Strike: heal on melee wounds).",
      equipment: ["Rune Sword", "Death Plate"],
      stats: { MOV: 5, ATK: 3, SKL: 3, STR: 5, TGH: 5, DEF: 4, INI: 3, WND: 3, PTS: 75 },
    },
    {
      name: "Necromancer",
      subfaction: "Scourge",
      tier: "Elite",
      archetype: "Caster / Summoner",
      keywords: ["Magical"],
      description: "The Scourge's engine. Living cultist — not Undead. Killing Necromancers cripples the Scourge. Choose spec: Plague (Cripple, Cloud of Disease) or Shadow (Shadow Bolt). Acolyte bodyguards generate Mana.",
      equipment: ["Bone Staff", "Rags/None"],
      stats: { MOV: 5, ATK: 1, SKL: 4, STR: 2, TGH: 3, DEF: 6, INI: 3, WND: 3, PTS: 55 },
    },
    {
      name: "Abomination",
      subfaction: "Scourge",
      tier: "Elite",
      archetype: "Monster",
      keywords: ["Undead", "Cleave", "Fear"],
      description: "Hulking construct of stitched corpses. Slow and inaccurate (SKL 5+) but devastating on contact — STR 7 triggers Armor Piercing against most targets. Plague Burst: on death, all non-Undead within 3\" suffer 1 Wound (no DEF save).",
      equipment: ["Meat Hook", "Death Plate"],
      stats: { MOV: 4, ATK: 4, SKL: 5, STR: 7, TGH: 6, DEF: 4, INI: 1, WND: 7, PTS: 100 },
    },
  ],
  composition: [
    { size: "Skirmish (500 pts)", baseline: "4-6", mounted: "0-1", elite: "0-2", hero: "1" },
    { size: "Standard (750 pts)", baseline: "5-8", mounted: "0-2", elite: "1-3", hero: "1-2" },
    { size: "Large (1000+ pts)", baseline: "6-10", mounted: "1-3", elite: "2-4", hero: "2-3" },
  ],
  specialRules: [
    "Most Scourge models have the Undead keyword: Immune to Morale, cannot be healed, immune to Taunt.",
    "Necromancers and Acolytes are living cultists. They test Morale normally and are the Mana generators. Killing them cripples the Scourge.",
    "Hero Bodyguards: DK (Mounted) gets 2 Ghouls, DK (On Foot) gets 2 Skeletons, Lich gets 3 Acolytes, Necromancer gets 2 Acolytes.",
  ],
};
